CREATE TABLE DWH_GEBOREN
(
    datensatz_id  number GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    jahr          number  NOT NULL,
    kalenderwoche number  NULL,
    -- 'L' für Lebend, 'T' für tot
    -- weil oracle hat kein boolean
    -- PostgreSQL viel besser - change my mind
    lebendgeburt  char(1) NULL,
    anzahl        number  NOT NULL,
    UNIQUE (jahr, KALENDERWOCHE, LEBENDGEBURT)
);

CREATE TABLE DWH_ALTERSGRUPPE
(
    altersgruppe_id varchar2(15) NOT NULL PRIMARY KEY,
    von             number       NOT NULL,
    bis             number       NOT NULL,
    UNIQUE (von, bis)
);

CREATE TABLE DWH_GESTORBEN
(
    datensatz_id         number GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    jahr                 number        NOT NULL,
    kalenderwoche        number        NULL,
    bundesland           varchar2(100) NULL,
    geschlecht           varchar2(100) NULL,
    altersgruppe_id      varchar2(15)  NULL,

    anzahl               number        NOT NULL,
    altersstd_sterberate number        NULL,

    FOREIGN KEY (altersgruppe_id) REFERENCES DWH_ALTERSGRUPPE (altersgruppe_id),
    UNIQUE (jahr, KALENDERWOCHE, BUNDESLAND, GESCHLECHT, ALTERSGRUPPE_ID)
);
